services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=3000

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
