version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: taskpilot-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taskpilot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskpilot-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskpilot-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/taskpilot?authSource=admin
      - PORT=3000
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongodb
    networks:
      - taskpilot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskpilot-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - taskpilot-network
    environment:
      - REACT_APP_API_URL=http://localhost:3000

networks:
  taskpilot-network:
    driver: bridge

volumes:
  mongodb_data:
