name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Lint Frontend
        run: |
          cd frontend
          npm run lint

      - name: Test Frontend
        run: |
          cd frontend
          npm test -- --watchAll=false

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Test Backend
        run: |
          cd backend
          npm test -- --watchAll=false
