name: Complete CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

env:
  STAGING_REGISTRY: taskpilot.azurecr.io
  PRODUCTION_REGISTRY: taskpilotacrvtzg5w.azurecr.io
  BACKEND_IMAGE: taskpilot-backend
  FRONTEND_IMAGE: taskpilot-frontend
  RESOURCE_GROUP: taskpilot-rg-vtzg5w
  BACKEND_CONTAINER_APP: taskpilot-backend
  FRONTEND_CONTAINER_APP: taskpilot-frontend

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test
        continue-on-error: true

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
        continue-on-error: true

  security:
    name: Security Scans
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      # CodeQL static analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: security-extended,security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"

      # Dependency scan for Node.js
      - name: Run npm audit
        run: |
          npm install
          npm audit --audit-level high
        continue-on-error: true

      # Container scan (Trivy)
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      # Secrets scan
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          base: main
          head: HEAD
          path: .
          extra_args: --debug --only-verified

  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: [test, security]
    outputs:
      backend-image-staging: ${{ steps.meta-backend-staging.outputs.tags }}
      frontend-image-staging: ${{ steps.meta-frontend-staging.outputs.tags }}
      backend-image-production: ${{ steps.meta-backend-production.outputs.tags }}
      frontend-image-production: ${{ steps.meta-frontend-production.outputs.tags }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1

      # Login to Azure CLI first
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Get ACR access tokens and set as environment variables
      - name: Get ACR Access Tokens
        run: |
          echo "STAGING_ACR_TOKEN=$(az acr credential show --name taskpilot --query 'passwords[0].value' -o tsv)" >> $GITHUB_ENV
          echo "PRODUCTION_ACR_TOKEN=$(az acr credential show --name taskpilotacrvtzg5w --query 'passwords[0].value' -o tsv)" >> $GITHUB_ENV

      # Login to Staging Registry using Docker Login Action
      - name: Login to Staging Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.STAGING_REGISTRY }}
          username: taskpilot
          password: ${{ env.STAGING_ACR_TOKEN }}

      # Login to Production Registry using Docker Login Action
      - name: Login to Production Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.PRODUCTION_REGISTRY }}
          username: taskpilotacrvtzg5w
          password: ${{ env.PRODUCTION_ACR_TOKEN }}

      # Build and push backend image to staging registry
      - name: Extract metadata for backend (staging)
        id: meta-backend-staging
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.STAGING_REGISTRY }}/${{ env.BACKEND_IMAGE }}
          tags: |
            type=raw,value=staging-latest

      - name: Build and push backend image to staging
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend-staging.outputs.tags }}
          labels: ${{ steps.meta-backend-staging.outputs.labels }}
          platforms: linux/amd64

      # Build and push frontend image to staging registry
      - name: Extract metadata for frontend (staging)
        id: meta-frontend-staging
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.STAGING_REGISTRY }}/${{ env.FRONTEND_IMAGE }}
          tags: |
            type=raw,value=staging-latest

      - name: Build and push frontend image to staging
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend-staging.outputs.tags }}
          labels: ${{ steps.meta-frontend-staging.outputs.labels }}
          platforms: linux/amd64

      # Build and push backend image to production registry
      - name: Extract metadata for backend (production)
        id: meta-backend-production
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PRODUCTION_REGISTRY }}/${{ env.BACKEND_IMAGE }}
          tags: |
            type=raw,value=production-latest

      - name: Build and push backend image to production
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta-backend-production.outputs.tags }}
          labels: ${{ steps.meta-backend-production.outputs.labels }}
          platforms: linux/amd64

      # Build and push frontend image to production registry
      - name: Extract metadata for frontend (production)
        id: meta-frontend-production
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PRODUCTION_REGISTRY }}/${{ env.FRONTEND_IMAGE }}
          tags: |
            type=raw,value=production-latest

      - name: Build and push frontend image to production
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-frontend-production.outputs.tags }}
          labels: ${{ steps.meta-frontend-production.outputs.labels }}
          platforms: linux/amd64

  image-scan:
    name: Scan Docker Images
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Staging Azure Container Registry
        run: |
          STAGING_TOKEN=$(az acr credential show --name taskpilot --query "passwords[0].value" -o tsv)
          echo $STAGING_TOKEN | docker login ${{ env.STAGING_REGISTRY }} --username taskpilot --password-stdin

      - name: Login to Production Azure Container Registry
        run: |
          PRODUCTION_TOKEN=$(az acr credential show --name taskpilotacrvtzg5w --query "passwords[0].value" -o tsv)
          echo $PRODUCTION_TOKEN | docker login ${{ env.PRODUCTION_REGISTRY }} --username taskpilotacrvtzg5w --password-stdin

      - name: Scan staging backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.STAGING_REGISTRY }}/${{ env.BACKEND_IMAGE }}:staging-latest
          format: 'sarif'
          output: 'staging-backend-trivy-results.sarif'

      - name: Scan staging frontend image
        uses: aquasecurity/trivy-action@master  
        with:
          image-ref: ${{ env.STAGING_REGISTRY }}/${{ env.FRONTEND_IMAGE }}:staging-latest
          format: 'sarif'
          output: 'staging-frontend-trivy-results.sarif'

      - name: Scan production backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.PRODUCTION_REGISTRY }}/${{ env.BACKEND_IMAGE }}:production-latest
          format: 'sarif'
          output: 'production-backend-trivy-results.sarif'

      - name: Scan production frontend image
        uses: aquasecurity/trivy-action@master  
        with:
          image-ref: ${{ env.PRODUCTION_REGISTRY }}/${{ env.FRONTEND_IMAGE }}:production-latest
          format: 'sarif'
          output: 'production-frontend-trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '.'
        continue-on-error: true

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, image-scan]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://taskpilot.azurewebsites.net
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'taskpilot-webapp'
          images: ${{ env.STAGING_REGISTRY }}/${{ env.BACKEND_IMAGE }}:staging-latest

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'taskpilot'
          images: ${{ env.STAGING_REGISTRY }}/${{ env.FRONTEND_IMAGE }}:staging-latest

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, image-scan]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://taskpilot-frontend.gentlewater-aa6fe06f.eastus2.azurecontainerapps.io
    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: ${{ github.repository_owner }}
          issue-title: "Production Deployment Approval Required"
          issue-body: |
            **Deployment Details:**
            - **Backend Image:** ${{ env.PRODUCTION_REGISTRY }}/${{ env.BACKEND_IMAGE }}:production-latest
            - **Frontend Image:** ${{ env.PRODUCTION_REGISTRY }}/${{ env.FRONTEND_IMAGE }}:production-latest
            - **Commit:** ${{ github.sha }}
            - **Branch:** ${{ github.ref_name }}
            
            Please review and approve this production deployment.

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: taskpilotacrvtzg5w
          containerAppName: ${{ env.BACKEND_CONTAINER_APP }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.PRODUCTION_REGISTRY }}/${{ env.BACKEND_IMAGE }}:production-latest

      - name: Deploy frontend to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: taskpilotacrvtzg5w
          containerAppName: ${{ env.FRONTEND_CONTAINER_APP }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToDeploy: ${{ env.PRODUCTION_REGISTRY }}/${{ env.FRONTEND_IMAGE }}:production-latest

  monitor:
    name: Post-Deployment Monitoring
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: always() && (needs.deploy-staging.result == 'success' || needs.deploy-production.result == 'success')
    steps:
      - name: Health Check - Staging
        if: needs.deploy-staging.result == 'success'
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://taskpilot.azurewebsites.net'
          max-attempts: 3
          retry-delay: 10s
          follow-redirect: true


      - name: Health Check - Production
        if: needs.deploy-production.result == 'success'
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://taskpilot-frontend.gentlewater-aa6fe06f.eastus2.azurecontainerapps.io'
          max-attempts: 3
          retry-delay: 10s
          follow-redirect: true

