name: Monitoring Health Check

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Frontend Health
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://taskpilot.azurewebsites.net'  
          max-attempts: 3
          retry-delay: 10s
          follow-redirect: true
        continue-on-error: true

      - name: Check Backend Health
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://taskpilot-webapp.azurewebsites.net/health'  
          max-attempts: 3
          retry-delay: 10s
          follow-redirect: true
        continue-on-error: true
