name: Complete CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      # Run unit and integration tests
      - name: Run Tests
        run: pytest --cov=.
      # Upload coverage report (optional)
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  security:
    name: Security Scans
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Static Application Security Testing
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      # Dependency Vulnerability Scanning
      - name: Install Safety
        run: pip install safety
      - name: Safety Check
        run: safety check --json
      # Container Security Scanning
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
      # Secrets Detection
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
      # Infrastructure Security
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4
      # Add your staging deployment steps here (e.g., AWS ECS, Kubernetes, etc.)

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      # Manual approval step
      - name: Await Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
      # Add your production deployment steps here

  monitor:
    name: Post-Deployment Monitoring
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    steps:
      - uses: actions/checkout@v4
      # Add health check and monitoring steps here
